name: Generate OpenAPI

on:
  workflow_run:
    workflows: ["CI-CD-images"]  # Name of the main workflow
    types:
      - completed

jobs:
  generate-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generate OpenAPI definition
      - name: Generate OpenAPI Definition
        run: |
          curl https://swagger-backend-container.whitehill-62ea132a.swedencentral.azurecontainerapps.io/swagger.json -o openapi.json  # Ensure your app is running and accessible
