name: openapi-gen

on:
  workflow_run:
    workflows: ["ci-cd"]
    types:
      - completed
  workflow_dispatch:  # To manually test the workflow in GitHub CLI

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Generate OpenAPI definition
      - name: Generate OpenAPI Definition
        run: |
          curl https://production-backend-container.whitehill-62ea132a.swedencentral.azurecontainerapps.io/apispec_1.json -o backend/openapi.json

      # Prettify the OpenAPI JSON
      - name: Prettify OpenAPI JSON
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          jq . backend/openapi.json > backend/openapi_pretty.json
          mv backend/openapi_pretty.json backend/openapi.json

      # Check for changes in the OpenAPI definition
      - name: Check for Changes
        run: |
          # Check for differences in the OpenAPI JSON file
          git diff --exit-code backend/openapi.json
          
          # Check exit code of the last command
          if [[ $? -ne 0 ]]; then
            echo "Changes detected."
          else
            echo "No changes detected."
            exit 0  # Exit the job early if no changes
          fi

      # Commit and push the updated OpenAPI definition only if there are changes
      - name: Commit and Push Changes
        run: |
          echo "Committing and pushing changes."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backend/openapi.json
          git commit -m "Update OpenAPI definition"
          git push
