name: openapi-gen

on:
  workflow_run:
    workflows: ["ci-cd"]
    types:
      - completed
  workflow_dispatch:  # To manually test the workflow in GitHub CLI

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Generate OpenAPI definition
      - name: Generate OpenAPI Definition
        run: |
          curl https://production-backend-container.whitehill-62ea132a.swedencentral.azurecontainerapps.io/apispec_1.json -o backend/openapi.json

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Set up the Git remote URL to use the GH_TOKEN for authentication
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/alexanderdarwiche/3TierWebApp.git

          git add backend/openapi.json
          git commit -m "Update OpenAPI definition"
          git push origin main
