name: openapi-gen

on:
  workflow_run:
    workflows: ["ci-cd"]
    types:
      - completed
  workflow_dispatch:  # To manually trigger the workflow in GitHub CLI

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Fetch the OpenAPI definition from your backend and save it to docs/openapi.json
      - name: Generate OpenAPI Definition
        run: |
          curl https://your-api-endpoint.com/apispec_1.json -o docs/openapi.json

      - name: Generate Markdown documentation
        run: |
          python docs/generate_docs.py
