name: openapi-gen

on:
  workflow_run:
    workflows: ["ci-cd"]
    types:
      - completed
  workflow_dispatch:  # To manually trigger the workflow in GitHub CLI

jobs:
  openapi-gen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Fetch the OpenAPI definition from the backend and save it to docs/openapi.json
      - name: Fetch OpenAPI definition
        run: |
          curl -o docs/.gitbook/assets/younium.json https://api.younium.com/swagger/v2/swagger.json
          curl -o docs/.gitbook/assets/youniumv2.json https://api.younium.com/swagger/v2.1/swagger.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/*
          git commit -m "Update openapi.json and API documentation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
