name: openapi-gen

on:
  workflow_run:
    workflows: ["ci-cd"]
    types:
      - completed
  workflow_dispatch:  # To manually trigger the workflow in GitHub CLI

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Fetch the OpenAPI definition from backend and save it to docs/openapi.json
      - name: Fetch OpenAPI definition
        run: |
          curl -o docs/openapi.json https://production-backend-container.whitehill-62ea132a.swedencentral.azurecontainerapps.io/apispec_1.json
    
      # Commit the fetched OpenAPI definition
      - name: Commit and push openapi.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/openapi.json
          git commit -m "Fetched openapi.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    
  update-documentation:
    runs-on: ubuntu-latest
    needs: generate-openapi  # Ensure this runs after generate-openapi job

    steps:
      - uses: actions/checkout@v4

      # Generate Markdown documentation
      - name: Generate Markdown documentation
        run: |
          python docs/generate_docs.py

      # Commit and push the generated documentation
      - name: Commit and push API documentation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/apidocs.md
          git commit -m "Update API documentation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
