name: Production API Documentation Sync

on:
  workflow_run:
    workflows: ["ci-cd"] # This should be on the workflow that updates the swagger file.
    types:
      - completed
  workflow_dispatch:  # To manually trigger the workflow in GitHub CLI

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  fetch_openapi:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Fetch OpenAPI definition
        run: |
          curl -o docs/.gitbook/assets/younium.json https://api.younium.com/swagger/v2/swagger.json
          curl -o docs/.gitbook/assets/youniumv2.json https://api.younium.com/swagger/v2.1/swagger.json

  generate_swagger_blocks:
    runs-on: ubuntu-latest
    needs: fetch_openapi
    env:
      API_ENVIRONMENT: production  # Default env variable is set to production in script. Remove to get dynamic result
    steps:
      - name: Generate Swagger blocks
        run: |
          python docs/generate_swagger.py

  generate_markdown_files:
    runs-on: ubuntu-latest
    needs: generate_swagger_blocks
    steps:
      - name: Generate separate markdown files
        run: |
          python docs/generate_md_files.py

  generate_summary:
    runs-on: ubuntu-latest
    needs: generate_markdown_files
    steps:
      - name: Generate SUMMARY.md
        run: |
          python docs/generate_summary.py

  commit_and_push:
    runs-on: ubuntu-latest
    needs: generate_summary
    steps:
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f docs/.gitbook/assets/*.json  # Force-add .json files even if ignored
          git add docs/
          git commit -m "Update OpenAPI files and markdown documentation in docs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

