name: Production API Documentation Sync

on:
  workflow_run:
    workflows: ["ci-cd"]  # This should be the workflow that updates the swagger file.
    types:
      - completed
  workflow_dispatch:  # To manually trigger the workflow in GitHub CLI

jobs:
  Generate-documentation:
    runs-on: ubuntu-latest
    env:
      API_ENVIRONMENT: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch OpenAPI definition
        run: |
          curl -o docs/.gitbook/assets/new_younium.json https://production-backend-container.whitehill-62ea132a.swedencentral.azurecontainerapps.io/apispec_1.json
          curl -o docs/.gitbook/assets/new_youniumv2.json https://api.younium.com/swagger/v2.1/swagger.json

      - name: Compare OpenAPI JSON files and determine changes
        id: check_changes
        run: |
          # Compare v1 JSON files
          if diff -q docs/.gitbook/assets/younium.json docs/.gitbook/assets/new_younium.json > /dev/null; then
            echo "v1: No changes detected"
            echo "V1_CHANGED=false" >> $GITHUB_ENV  # No changes in v1
          else
            echo "v1: Changes detected"
            echo "V1_CHANGED=true" >> $GITHUB_ENV  # Changes detected in v1
          fi

          # Compare v2 JSON files
          if diff -q docs/.gitbook/assets/youniumv2.json docs/.gitbook/assets/new_youniumv2.json > /dev/null; then
            echo "v2: No changes detected"
            echo "V2_CHANGED=false" >> $GITHUB_ENV  # No changes in v2
          else
            echo "v2: Changes detected"
            echo "V2_CHANGED=true" >> $GITHUB_ENV  # Changes detected in v2
          fi

      - name: Check if changes exist in either file
        run: |
          if [[ "$V1_CHANGED" == "false" && "$V2_CHANGED" == "false" ]]; then
            echo "No changes in either file, stopping workflow."
            exit 0
          else
            echo "Changes detected, proceeding with documentation generation."
          fi
          
      - name: Cleanup old JSON files
        if: env.V1_CHANGED == 'true' || env.V2_CHANGED == 'true'  # Only run if there are changes
        run: |
          mv docs/.gitbook/assets/new_younium.json docs/.gitbook/assets/younium.json
          mv docs/.gitbook/assets/new_youniumv2.json docs/.gitbook/assets/youniumv2.json

      - name: Generate Swagger blocks
        if: env.V1_CHANGED == 'true' || env.V2_CHANGED == 'true'  # Only run if there are changes
        run: |
          python scripts/generate_swagger.py

      - name: Generate separate markdown files
        if: env.V1_CHANGED == 'true' || env.V2_CHANGED == 'true'  # Only run if there are changes
        run: |
          python scripts/generate_md_files.py

      - name: Generate SUMMARY.md
        if: env.V1_CHANGED == 'true' || env.V2_CHANGED == 'true'  # Only run if there are changes
        run: |
          python scripts/generate_summary.py

      - name: Commit and push changes
        if: env.V1_CHANGED == 'true' || env.V2_CHANGED == 'true'  # Only run if there are changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f docs/.gitbook/assets/*.json  # Force-add .json files even if ignored
          git add docs/
          git commit -m "Update OpenAPI files and markdown documentation in docs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
