name: Production API Documentation Sync

on:
  workflow_run:
    workflows: ["ci-cd"]  # This should be the workflow that updates the swagger file.
    types:
      - completed
  workflow_dispatch:  # To manually trigger the workflow in GitHub CLI

jobs:
  sync_docs:
    runs-on: ubuntu-latest
    env:
      API_ENVIRONMENT: production  # Default value in generate_swagger script is set to production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch OpenAPI definition
        run: |
          curl -o docs/.gitbook/assets/younium.json https://api.younium.com/swagger/v2/swagger.json
          curl -o docs/.gitbook/assets/youniumv2.json https://api.younium.com/swagger/v2.1/swagger.json

      - name: Generate Swagger blocks
        run: |
          python docs/generate_swagger.py
          
      - name: Generate separate markdown files
        run: |
          python docs/generate_md_files.py
          
      - name: Generate SUMMARY.md
        run: |
          python docs/generate_summary.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f docs/.gitbook/assets/*.json  # Force-add .json files even if ignored
          git add docs/
          git commit -m "Update OpenAPI files and markdown documentation in docs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
