name: Docker Image CI and Deploy to Azure

on:
  push:
    branches:
      - azure  # Trigger on push to the azure branch
  pull_request:
    branches:
      - azure  # Trigger on pull requests to the azure branch

env:
  CONTAINER_REGISTRY: todoregister.azurecr.io  # Azure Container Registry
  BACKEND_IMAGE: todoregister.azurecr.io/azure-backend:latest
  FRONTEND_IMAGE: todoregister.azurecr.io/azure-frontend:latest
  RESOURCE_GROUP: todo-rg
  BACKEND_CONTAINER: azure-backend-container
  FRONTEND_CONTAINER: azure-frontend-container
  AZURE_ENVIRONMENT: todo-container-env

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Authentication
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure this contains your JSON credentials

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build and tag the Docker image for the backend
      - name: Build and tag backend Docker image
        run: docker build ./backend -t ${{ env.BACKEND_IMAGE }}

      # Push the backend image to Azure Container Registry
      - name: Push backend image to ACR
        run: docker push ${{ env.BACKEND_IMAGE }}

      # Create backend container app if it doesn't exist
      - name: Create backend Container App
        run: |
          az containerapp create --name ${{ env.BACKEND_CONTAINER }} \
                                  --resource-group ${{ env.RESOURCE_GROUP }} \
                                  --image ${{ env.BACKEND_IMAGE }} \
                                  --environment ${{ env.AZURE_ENVIRONMENT }} \
                                  --min-replicas 1 \
                                  --max-replicas 5 \
                                  --cpu 0.5 \
                                  --memory 1.0Gi

      # Deploy backend container app to Azure
      - name: Deploy backend to Azure Container Apps
        run: |
          az containerapp update --name ${{ env.BACKEND_CONTAINER }} \
                                 --resource-group ${{ env.RESOURCE_GROUP }} \
                                 --image ${{ env.BACKEND_IMAGE }} \
                                 --set environmentVariables.DATABASE_HOST=mysql-container \
                                     environmentVariables.DATABASE_USER=appuser \
                                     environmentVariables.DATABASE_PORT=3306 \
                                     environmentVariables.DATABASE_PASSWORD=apppassword \
                                     environmentVariables.DATABASE_NAME=app_db

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Authentication
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure this contains your JSON credentials

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build and tag the Docker image for the frontend
      - name: Build and tag frontend Docker image
        run: docker build ./frontend -t ${{ env.FRONTEND_IMAGE }}

      # Push the frontend image to Azure Container Registry
      - name: Push frontend image to ACR
        run: docker push ${{ env.FRONTEND_IMAGE }}

      # Create frontend container app if it doesn't exist
      - name: Create frontend Container App
        run: |
          az containerapp create --name ${{ env.FRONTEND_CONTAINER }} \
                                  --resource-group ${{ env.RESOURCE_GROUP }} \
                                  --image ${{ env.FRONTEND_IMAGE }} \
                                  --environment ${{ env.AZURE_ENVIRONMENT }} \
                                  --min-replicas 1 \
                                  --max-replicas 5 \
                                  --cpu 0.5 \
                                  --memory 1.0Gi

      # Deploy frontend container app to Azure
      - name: Deploy frontend to Azure Container Apps
        run: |
          az containerapp update --name ${{ env.FRONTEND_CONTAINER }} \
                                 --resource-group ${{ env.RESOURCE_GROUP }} \
                                 --image ${{ env.FRONTEND_IMAGE }} \
                                 --set environmentVariables.REACT_APP_BACKEND_URL=https://backend-container.whitehill-62ea132a.swedencentral.azurecontainerapps.io
