name: Push to azure registry

on:
  workflow_run:
    workflows: ["push-image.yml"]  # The name of the first workflow
    types:
      - completed  # Trigger after the first workflow completes successfully

jobs:
  # Job for backend Docker image
  todo-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login todoregister.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

    - name: Build the Docker image for backend
      run: docker build ./backend -t todoregister.azurecr.io/testazure-backend:latest

    - name: Push backend image to Azure Container Registry
      run: docker push todoregister.azurecr.io/testazure-backend:latest

  # Job for frontend Docker image
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login todoregister.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

    - name: Build the Docker image for frontend
      run: docker build ./frontend -t todoregister.azurecr.io/testazure-frontend:latest

    - name: Push frontend image to Azure Container Registry
      run: docker push todoregister.azurecr.io/testazure-frontend:latest
