name: Sandbox API Documentation Sync

on:
  workflow_run:
    workflows: ["ci-cd"]  # This should be the workflow that updates the swagger file.
    types:
      - completed
  workflow_dispatch:  # To manually trigger the workflow in GitHub CLI

jobs:
  sync_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch OpenAPI definition
        run: |
          curl -o docs-sandbox/.gitbook/assets/younium-sandbox.json https://api.sandbox.younium.com/swagger/v2/swagger.json
          curl -o docs-sandbox/.gitbook/assets/youniumv2-sandbox.json https://api.sandbox.younium.com/swagger/v2.1/swagger.json

      - name: Generate Swagger blocks
        env:
          API_ENVIRONMENT: sandbox  # Default value in generate_swagger script is set to production
        run: |
          python docs/generate_swagger.py

      - name: Generate separate markdown files
        run: |
          python docs/generate_md_files.py

      - name: Generate SUMMARY.md
        run: |
          python docs/generate_summary_sandbox.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f docs-sandbox/.gitbook/assets/*.json  # Force-add .json files even if ignored
          git add docs-sandbox/
          git commit -m "Update OpenAPI files and markdown documentation in docs-sandbox"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
